#!/usr/bin/env bash
# Install Nginx
sudo apt-get update
sudo apt-get install nginx

# Configure Nginx
sudo sed -i 's/# server_names_hash_bucket_size 64;/server_names_hash_bucket_size 64;/g' /etc/nginx/nginx.conf
sudo sed -i 's/listen \[::\]:80 default_server;/listen 80 default_server;/g' /etc/nginx/sites-available/default

# Restart Nginx
sudo systemctl restart nginx
