#!/usr/bin/env bash
# Install Nginx
sudo apt-get update
sudo apt-get install nginx

# Configure Nginx
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# Restart Nginx
sudo systemctl restart nginx
