#!/usr/bin/env bash
# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Configure Nginx to listen on port 80
sudo sed -i 's/# listen 80;/listen 80;/g' /etc/nginx/sites-available/default

# Allow traffic on port 80 through the firewall
sudo ufw allow 80/tcp

# Restart Nginx
sudo systemctl restart nginx

