#!/usr/bin/env bash
# Creates the file /var/run/myscript.pid containing its PID,
# Displays 'To infinity and beyond' indefinitely, 
# Displays 'Y U no love me?!' when receiving a SIGINT signal,
# Displays 'I hate the kill command' when it receives a SIGTERM signal, and
# Deletes /var/run/myscript.pid and terminates on SIGQUIT or SIGTERM signal.

trap onClose QUIT
trap onTERM TERM

function onTERM()
{
    echo I hate the kill command
    onClose
}
function onClose()
{
    rm -f /var/run/myscript.pid
	exit
}

echo $$ > /var/run/myscript.pid

while true; do
    echo To infinity and beyond
    sleep 2

    trap 'echo Y U no love me?!' INT
done
