#!/usr/bin/env bash
# Like 1-list_your_processes, but displays only lines containing the bash word, thus allowing you to easily get the PID of your Bash process (without using pgrep).
# shellcheck disable=SC2009
ps auxf | grep 'bash'
