#!/usr/bin/env bash
# Displays 'To infinity and beyond' indefinitely, and prints 'I am invincible!!!' when it receives a SIGTERM signal.

while true; do
    echo To infinity and beyond
    sleep 2

    trap 'echo I am invincible!!!' TERM
done
