#!/usr/bin/env bash
# Displays the username, user id, and home path for each user in /etc/passwd.

if [ -e "/etc/passwd" ]; then
    while read -r line; do
	echo "$line" | cut -d":" -f1,3,6
    done < /etc/passwd
fi
