#!/usr/bin/env bash
# Displays the contents of /etc/passwd as a story, using a while loop + IFS.
# FORMAT: The user USERNAME is part of the GROUP_ID gang, lives in HOME_DIRECTORY and rides COMMAND/SHELL. USER ID's place is protected by the passcode PASSWORD, more info about the user here: USER ID INFO

IFS_backup=$IFS
IFS=:

if [ -e "/etc/passwd" ]; then
    while read -ra line; do
	echo "The user ${line[0]} is part of the ${line[3]} gang, lives in ${line[5]} and rides ${line[6]}. ${line[2]}'s place is protected by the passcode ${line[1]}, more info about the user here: ${line[4]}"
    done < /etc/passwd
fi

IFS=$IFS_backup
