#!/usr/bin/env bash
# Displays the visitor IPs and HTTP status codes from an Apache log file.

if [ -e "apache-access.log" ] && [ -f "apache-access.log" ]; then
    awk -F' ' '{ print($1, $9) }' < apache-access.log
fi
