#!/usr/bin/env bash
# Displays "Best School" ten times using a while loop. Adds "Hi" nineth time.
# shellcheck disable=SC2034

i=1
while [ $i -le 10 ]; do
    echo "Best School"
    if [ $i -eq 9 ]; then
	echo "Hi"
    fi
    (( i++ ))
done
