#!/usr/bin/env bash
# Displays the time for 12 hours and 59 minutes: hours 0-12, minutes 1-59.
# shellcheck disable=SC2034

hour=0
while [ $hour -le 12 ]; do
    echo "Hour: $hour"
    (( hour++ ))

    min=1
    while [ $min -le 59 ]; do
	echo $min
	(( min++ ))
    done
done
